# Generated by Django 5.2.4 on 2025-09-28 13:16

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер авто')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я водія")),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('company', models.CharField(max_length=200, verbose_name='Фірма')),
                ('quantity_per_pallet', models.IntegerField(help_text='Скільки одиниць товару міститься на одній повній палеті.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість на палеті')),
                ('total_units', models.IntegerField(default=0, help_text='Загальна кількість картонів <в штуках>', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Загальний залишок (шт.)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('low_threshold', models.IntegerField(default=15000, help_text='Мінімальне порогове значення наповнюваності для цього продукту <в штуках>', verbose_name='Рівень мінімальної кількості шт.')),
                ('normal_threshold', models.IntegerField(default=66000, help_text='Максимальне порогове значення наповнюваності для цього продукту <в штуках>', verbose_name='Рівень максимальної кількості шт.')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(help_text='Назва компанії або особи, що доставила товар', max_length=200, verbose_name='Постачальник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('PENDING', 'В очікуванні'), ('COMPLETED', 'Завершено')], default='PENDING', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Постачання',
                'verbose_name_plural': 'Постачання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час початку')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Час закінчення')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Робоча зміна',
                'verbose_name_plural': 'Робочі зміни',
                'db_table': 'inventory_workshift',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, verbose_name='Номер авто')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Автомобіль',
                'verbose_name_plural': 'historical Автомобілі',
                'db_table': 'car_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDriver',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я водія")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Водій',
                'verbose_name_plural': 'historical Водії',
                'db_table': 'driver_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('company', models.CharField(max_length=200, verbose_name='Фірма')),
                ('quantity_per_pallet', models.IntegerField(help_text='Скільки одиниць товару міститься на одній повній палеті.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість на палеті')),
                ('total_units', models.IntegerField(default=0, help_text='Загальна кількість картонів <в штуках>', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Загальний залишок (шт.)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('low_threshold', models.IntegerField(default=15000, help_text='Мінімальне порогове значення наповнюваності для цього продукту <в штуках>', verbose_name='Рівень мінімальної кількості шт.')),
                ('normal_threshold', models.IntegerField(default=66000, help_text='Максимальне порогове значення наповнюваності для цього продукту <в штуках>', verbose_name='Рівень максимальної кількості шт.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Продукт',
                'verbose_name_plural': 'historical Продукти',
                'db_table': 'product_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSupply',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('supplier', models.CharField(help_text='Назва компанії або особи, що доставила товар', max_length=200, verbose_name='Постачальник')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('PENDING', 'В очікуванні'), ('COMPLETED', 'Завершено')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Постачання',
                'verbose_name_plural': 'historical Постачання',
                'db_table': 'supply_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWorkShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час початку')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Час закінчення')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Робоча зміна',
                'verbose_name_plural': 'historical Робочі зміни',
                'db_table': 'work_shift_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200, verbose_name='Замовник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('PENDING', 'В очікуванні'), ('SHIPPED', 'Виїхало'), ('LOADED', 'Готове/Завантажено'), ('CANCELLED', 'Скасовано')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='В архіві')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('delivery_date', models.DateField(default=datetime.date(2025, 9, 28), verbose_name='Дата доставки')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.car', verbose_name='Автомобіль')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.driver', verbose_name='Водій')),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.workshift', verbose_name='Робоча зміна')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrderItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ordered_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Замовлено (шт.)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'historical Позиція замовлення',
                'verbose_name_plural': 'historical Позиції замовлення',
                'db_table': 'order_item_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(verbose_name='Зміна кількості')),
                ('new_total_units', models.IntegerField(verbose_name='Новий залишок (шт.)')),
                ('movement_type', models.CharField(choices=[('SUPPLY_IN', 'Надходження від постачання'), ('ORDER_OUT', 'Резервування під замовлення'), ('ORDER_RETURN', 'Повернення (скасування/редагування)'), ('MANUAL_ADJUST', 'Ручне коригування')], max_length=20, verbose_name='Тип транзакції')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час транзакції')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примітки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Продукт')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.order', verbose_name="Пов'язане замовлення")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('related_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supply', verbose_name="Пов'язане постачання")),
            ],
            options={
                'verbose_name': 'Рух по складу',
                'verbose_name_plural': 'Рух по складу',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplyItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість (шт.)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Товар')),
                ('supply', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.supply', verbose_name='Постачання')),
            ],
            options={
                'verbose_name': 'historical Позиція постачання',
                'verbose_name_plural': 'historical Позиції постачання',
                'db_table': 'supply_item_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStockMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity_change', models.IntegerField(verbose_name='Зміна кількості')),
                ('new_total_units', models.IntegerField(verbose_name='Новий залишок (шт.)')),
                ('movement_type', models.CharField(choices=[('SUPPLY_IN', 'Надходження від постачання'), ('ORDER_OUT', 'Резервування під замовлення'), ('ORDER_RETURN', 'Повернення (скасування/редагування)'), ('MANUAL_ADJUST', 'Ручне коригування')], max_length=20, verbose_name='Тип транзакції')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час транзакції')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примітки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('related_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.order', verbose_name="Пов'язане замовлення")),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Продукт')),
                ('related_supply', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.supply', verbose_name="Пов'язане постачання")),
            ],
            options={
                'verbose_name': 'historical Рух по складу',
                'verbose_name_plural': 'historical Рух по складу',
                'db_table': 'stock_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('customer', models.CharField(max_length=200, verbose_name='Замовник')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('PENDING', 'В очікуванні'), ('SHIPPED', 'Виїхало'), ('LOADED', 'Готове/Завантажено'), ('CANCELLED', 'Скасовано')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='В архіві')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('delivery_date', models.DateField(default=datetime.date(2025, 9, 28), verbose_name='Дата доставки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('car', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.car', verbose_name='Автомобіль')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.driver', verbose_name='Водій')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.workshift', verbose_name='Робоча зміна')),
            ],
            options={
                'verbose_name': 'historical Замовлення',
                'verbose_name_plural': 'historical Замовлення',
                'db_table': 'order_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Замовлено (шт.)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість (шт.)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supply', verbose_name='Постачання')),
            ],
            options={
                'verbose_name': 'Позиція постачання',
                'verbose_name_plural': 'Позиції постачання',
                'unique_together': {('supply', 'product')},
            },
        ),
    ]
