# Generated by Django 5.2.4 on 2025-10-19 11:58

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='delivery_date',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=inventory.models.get_current_date, verbose_name='Дата доставки'),
        ),
    ]
