# Generated by Django 5.2.4 on 2025-10-19 12:54

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkshift',
            name='start_time',
            field=models.DateTimeField(default=inventory.models.get_current_date, verbose_name='Час початку'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.DateTimeField(default=inventory.models.get_current_date, verbose_name='Час початку'),
        ),
    ]
