# Generated by Django 5.2.4 on 2025-10-19 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_historicalworkshift_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkshift',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час початку'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час початку'),
        ),
    ]
