# Generated by Django 5.2.4 on 2026-04-06 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_historicalworkshift_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='allow_credit',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено, можна продавати товар в кредит, навіть якщо його немає на складі.', verbose_name='Дозволити продаж в кредит'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='credit_units',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кількість в кредиті (борг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='allow_credit',
            field=models.BooleanField(default=False, help_text='Якщо увімкнено, можна продавати товар в кредит, навіть якщо його немає на складі.', verbose_name='Дозволити продаж в кредит'),
        ),
        migrations.AddField(
            model_name='product',
            name='credit_units',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кількість в кредиті (борг)'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В очікуванні'), ('SHIPPED', 'Виїхало'), ('LOADED', 'Готове/Завантажено'), ('CANCELLED', 'Скасовано'), ('DOCUMENTS', 'Документи')], default='PENDING', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В очікуванні'), ('SHIPPED', 'Виїхало'), ('LOADED', 'Готове/Завантажено'), ('CANCELLED', 'Скасовано'), ('DOCUMENTS', 'Документи')], default='PENDING', max_length=10, verbose_name='Статус'),
        ),
    ]
